version: "3"
services:
  appserver:
    container_name: server
    hostname: localhost
    image: syntheticborealis/spring-reactive-search:latest
    links:
      - redis
    ports:
      - "8080:8080"

  redis:
    image: redis
    ports:
      - 6379:6379
    privileged: true
